// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmcepwdqvrpydjcgkyud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtY2Vwd2RxdnJweWRqY2dreXVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNDk1OTYsImV4cCI6MjA2ODgyNTU5Nn0.7w3zi7UecahJU-fepZWPavkPhGh1wIv_2-iMp3z8cLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});